<h1 style="text-align:center">Tarea 2 - Transformada discreta de Fourier</h1>
<h2 style="text-align:center"> ACUS099: Procesamiento Digital de Señales </h2>

<p style="text-align:center"> <b>Grupo: </b></p>
<p style="text-align:center">Nicolás Montes Alvarado <br>
<a href="mailto:nicolas.montes@alumnos.uach.cl">nicolas.montes@alumnos.uach.cl</a><br>

<p style="text-align:center"> <b>Profesor </b></p>
<p style="text-align:center">Dr. Víctor Poblete R. <br>
<a href="mailto:vpoblete@uach.cl">vpoblete@uach.cl</a><br>

<p style="text-align:center"> <b>Ayudantes </b></p>

<p style="text-align:center">Diego Espejo A.<br>
<a href="mailto:vpoblete@uach.cl">diego.espejo@alumnos.uach.cl</a><br>
    
<p style="text-align:center">Esteban Vargas C.<br>
<a href="mailto:vpoblete@uach.cl">esteban.vargas01@alumnos.uach.cl</a><br>

En la siguiente tarea, se crearan en Python dos funciones: Una de Transformada Discreta de Fourier, y su inversa.

Para efectos de comparación, y el uso de las funciones matemáticas, importamos numpy y su función fft:

In [1]:
from numpy import fft
import numpy as np

En la siguiente función, denominada "Fourier", se reciben un argumento, el cual es un array determinado a transformar. La función lo imprime, y calsula su Twiddle Factor, el cual matemáticamente es:

<h3 style="text-align:center">$\Large W_n = e^{\frac{2\pi*-j}{N}}$</h3>
siendo N equivalente al largo del vector.

Una vez realizado esto, se genera su matriz de transformación:
<h3 style="text-align:center">$\Large M = \sum_{k=0}^{N-1}(\sum_{n=0}^{N-1}W_n^{k*n})$</h3>

Finalmente, se hace un producto punto de la matriz con el vector de entrada:

<h3 style="text-align:center">$\Large DFT = M*x$</h3>

In [2]:
def Fourier(x):
    N = len(x)
    print("Funcion Discreta de Fourier:")
    print()
    
    print("Vector Original:")
    print(x)
    print()
    
    W_n=np.exp((2*np.pi*-1j)/N)
    print("- Twiddle Factor:")
    print(W_n)
    print()
    
    M=np.zeros((N,N),dtype=complex)
    for k in range(N):
        for n in range(N):
            M[k,n]=W_n**(k*n)
    print("- Matriz de Transformacion:")
    print(M)
    print()
    
    print("- Funcion FFT Python:")
    print(np.fft.fft(x))
    print()
    
    X=np.dot(M,x)
    print("- Resultado Funcion Fourier:")
    print(X)
    
    print()
    print()
    return(X)

Para posteriormente invertir la función, se redondea el vector de entrada y se calcula nuevamente el mismo Twiddle Factor.
Para generar su matriz de transformación, se multiplica de la siguiente forma:
<h3 style="text-align:center">$\Large M = \frac{1}{N}\sum_{k=0}^{N-1}(\sum_{n=0}^{N-1}W_n^{-k*n})$</h3>

Y se hace producto punto de la misma forma:
<h3 style="text-align:center">$\Large DFT = M*X$</h3>

In [3]:
def InvFourier(X):
    N = len(X)
    print("Funcion Inversa Discreta de Fourier:")
    print()
    
    print("Vector Original:")
    print(X)
    print()
    
    #Es necesario remover warnings en la funcion
    #para asi poder concatenar numeros complejos en int
    import warnings
    warnings.filterwarnings("ignore")
    
    X=np.around(X,0)
    
    W_n=np.exp((2*np.pi*-1j)/N)
    print("- Twiddle Factor: ")
    print(W_n)
    print()
    
    M=np.zeros((N,N),dtype=complex)
    for k in range(N):
        for n in range(N):
            M[k,n]=(1/N)*W_n**(-k*n)
    print("- Matriz de Transformacion:")
    print(M)
    print()
    
    ifftXComplex = np.dot(M,X)
    x = np.zeros(len(ifftXComplex), dtype = int)
    for i in range(N):
        x[i] = int(np.around(ifftXComplex[i],0))
    warnings.resetwarnings()
    print("- Resultado Funcion Inversa de Fourier:")
    print(x)
    
    print()
    print()
    return(x)

En la siguiente sección, generaremos 3 vectores azarosos distintos, de tamaños 5, 20 y 50, y con limites entre 0 a 9 para cada valor numérico interno. Los limites se consideraron principalmente para que no se generen valores excesivamente grandes en este experimento:

In [4]:
N1 = 5
x1 = np.random.randint(10,size=N1)
print("Vector de 5:")
print(x1)
N2 = 20
x2 = np.random.randint(10,size=N2)
print("Vector de 20:")
print(x2)
N3 = 50
x3 = np.random.randint(10,size=N3)
print("Vector de 50:")
print(x3)

Vector de 5:
[6 1 7 3 6]
Vector de 20:
[6 1 9 6 0 9 9 4 2 1 9 7 3 4 6 7 4 7 0 4]
Vector de 50:
[7 2 3 6 8 0 5 6 3 7 2 5 1 2 3 5 7 9 9 5 0 6 0 0 1 3 9 2 7 2 4 6 7 1 1 1 1
 2 0 0 8 0 7 9 8 7 0 6 7 8]


Finalmente, anidamos ambas funciones, lo cual nos entrega los resultados impresos en el codigo. Podemos apreciar que los resultados son exactamente los mismos a la función integrada en python, y al invertirse, devuelve los mismos valores.

In [5]:
InvFourier(Fourier(x1))
InvFourier(Fourier(x2))
InvFourier(Fourier(x3))

Funcion Discreta de Fourier:

Vector Original:
[6 1 7 3 6]

- Twiddle Factor:
(0.30901699437494745-0.9510565162951535j)

- Matriz de Transformacion:
[[ 1.        +0.j          1.        +0.j          1.        +0.j
   1.        +0.j          1.        +0.j        ]
 [ 1.        +0.j          0.30901699-0.95105652j -0.80901699-0.58778525j
  -0.80901699+0.58778525j  0.30901699+0.95105652j]
 [ 1.        +0.j         -0.80901699-0.58778525j  0.30901699+0.95105652j
   0.30901699-0.95105652j -0.80901699+0.58778525j]
 [ 1.        +0.j         -0.80901699+0.58778525j  0.30901699-0.95105652j
   0.30901699+0.95105652j -0.80901699-0.58778525j]
 [ 1.        +0.j          0.30901699+0.95105652j -0.80901699+0.58778525j
  -0.80901699-0.58778525j  0.30901699-0.95105652j]]

- Funcion FFT Python:
[23.        +0.j          0.07294902+2.40414157j  3.42705098+6.74315233j
  3.42705098-6.74315233j  0.07294902-2.40414157j]

- Resultado Funcion Fourier:
[23.        +0.j          0.07294902+2.40414157j  3.42705

array([7, 2, 3, 6, 8, 0, 5, 6, 3, 7, 2, 5, 1, 2, 3, 5, 7, 9, 9, 5, 0, 6,
       0, 0, 1, 3, 9, 2, 7, 2, 4, 6, 7, 1, 1, 1, 1, 2, 0, 0, 8, 0, 7, 9,
       8, 7, 0, 6, 7, 8])

Para finalizar, podemos concluir primero que la Función Discreta de Fourier es completamente invertible. A través de la técnica del Twiddle Factor con su Matriz anidada, podemos llegar a los mismos resultados que la función integrada en NumPy (aunque cabe destacar que con mucha menos eficiencia de recursos para el computador).
Fue necesario recurrir a la función "filterwarnings()" para poder concatenar con éxito el resultado de la función de Fourier Inversa a los Int() originales. Probablemente sea necesario hacer lo mismo para float() si esos son los valores de ingreso; Esto ya que Python indica un error al eliminar los valores imaginarios, aún cuando se asume que en el caso de la función inversa, estos van a ser equivalentes a 0.